
FROM python:3.10-slim


WORKDIR /app


RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libgl1 libglib2.0-0 build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

# Copy only requirements 
COPY requirement.txt .


RUN pip install --no-cache-dir -r requirement.txt


COPY app/ .


EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
